# -*- coding: utf-8 -*-
"""바이브코딩과제_2026420035조수아

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qzJSxSEmxWXz1KrRvcvYmug2MQlupXfz
"""

import random

def distribute_roles():
    print("=== 🎯 팀원 성향 맞춤형 최적 팀플 역할 분배기 ===\n")

    # 1단계: 역할 종류 입력 및 사람 수 확정
    role_input = input("이번 팀플에 필요한 역할들을 쉼표(,)로 구분해서 입력해주세요\n(예: 자료조사, PPT, 발표, 총괄): ")

    # 입력받은 문자열을 리스트로 변환하고 양옆 공백 제거
    required_roles = [role.strip() for role in role_input.split(',')]
    num_members = len(required_roles)

    print(f"\n▶ 총 {num_members}개의 역할이 확인되었습니다.")
    print(f"▶ 역할 수와 동일하게 팀원 {num_members}명의 정보를 입력받습니다.\n")
    print("-" * 40)

    # 2단계: 팀원 데이터 수집 (이름, 1지망, 2지망, 기피)
    team_members = {}

    for i in range(num_members):
        print(f"[{i+1}번째 팀원 정보 입력]")
        name = input("이름: ")
        first_choice = input(f"{name} 님의 1지망 역할: ")
        second_choice = input(f"{name} 님의 2지망 역할: ")
        avoid_choice = input(f"{name} 님의 절대 기피 역할: ")

        # 딕셔너리 저장
        team_members[name] = {
            "1st": first_choice.strip(),
            "2nd": second_choice.strip(),
            "avoid": avoid_choice.strip()
        }
        print() # 입력 간격 구분을 위한 줄바꿈

    print("-" * 40)
    print("🤖 AI가 최적의 조합을 계산하고 있습니다...\n")

    # 3단계: 역할 매칭 (조건문) 및 예외 상황(난수) 처리
    assigned_result = {}
    unassigned_roles = required_roles.copy()
    unassigned_members = list(team_members.keys())

    # [우선순위 1] 1지망 배정
    for role in list(unassigned_roles):
        candidates = [m for m in unassigned_members if team_members[m]["1st"] == role]
        if candidates:
            chosen = random.choice(candidates)
            assigned_result[chosen] = {"role": role, "reason": "1지망 반영"}
            unassigned_members.remove(chosen)
            unassigned_roles.remove(role)

    # [우선순위 2] 2지망 배정 (남은 인원과 남은 역할 대상)
    for role in list(unassigned_roles):
        candidates = [m for m in unassigned_members if team_members[m]["2nd"] == role]
        if candidates:
            chosen = random.choice(candidates)
            assigned_result[chosen] = {"role": role, "reason": "2지망 반영"}
            unassigned_members.remove(chosen)
            unassigned_roles.remove(role)

    # [우선순위 3] 기피 분야 제외 랜덤 배정 및 최종 예외 처리
    for role in list(unassigned_roles):
        # 기피 분야가 아닌 사람 후보군
        candidates = [m for m in unassigned_members if team_members[m]["avoid"] != role]

        if candidates:
            chosen = random.choice(candidates)
            assigned_result[chosen] = {"role": role, "reason": "기피 분야 제외 랜덤 배정"}
            unassigned_members.remove(chosen)
            unassigned_roles.remove(role)
        else:
            # 예외: 남은 사람 모두가 해당 역할을 기피할 경우 무작위 배정
            if unassigned_members:
                chosen = random.choice(unassigned_members)
                assigned_result[chosen] = {"role": role, "reason": "모두 기피하여 불가피한 랜덤 배정"}
                unassigned_members.remove(chosen)
                unassigned_roles.remove(role)

    # 4단계: 최종 팀플 가이드라인 출력 (f-string)
    print("=" * 40)
    print("🎉 [최종 팀플 역할 분배 결과] 🎉")
    print("=" * 40)

    # 입력된 사람 순서가 아닌, 깔끔하게 정리된 딕셔너리 기준으로 출력
    for name, info in assigned_result.items():
        print(f"▶ {name} 님: {info['role']} ({info['reason']})")

    print("=" * 40)
    print("성공적인 팀 프로젝트를 응원합니다!\n")

# 프로그램 실행
if __name__ == "__main__":
    distribute_roles()